"""Adding withdrawal request table

Revision ID: 2e86c0c9898e
Revises: 8c108d6f6f53
Create Date: 2025-02-03 22:46:31.094271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e86c0c9898e'
down_revision = '8c108d6f6f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=True),
    sa.Column('rejections', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_request')
    # ### end Alembic commands ###
