"""Add mpesa_transaction_id to WithdrawalRequest

Revision ID: 62a9950b6b58
Revises: 1c3b889b4139
Create Date: 2025-02-17 14:32:53.023486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a9950b6b58'
down_revision = '1c3b889b4139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['mpesa_transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
