"""Add daily_contribution_amount to Group

Revision ID: dc1d971ef1c4
Revises: d6597bf02fa1
Create Date: 2025-08-25 19:59:21.148825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1d971ef1c4'
down_revision = 'd6597bf02fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_contribution_amount', sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('daily_contribution_amount')

    # ### end Alembic commands ###
