"""Add receipt_number to transactions table

Revision ID: eabe0a228bd6
Revises: e1afc84781ad
Create Date: 2025-02-12 15:34:34.021358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabe0a228bd6'
down_revision = 'e1afc84781ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
